var dataMap={};
dataMap.OV={
	1980:[
		{name: 'Alabama', value: 557},
		{name: 'Alaska', value: 48},
		{name: 'Arizona', value: 329},
		{name: 'Arkansas', value: 232},
		{name: 'California', value: 3880},
		{name: 'Colorado', value: 208},
		{name: 'Connecticut', value: 168},
		{name: 'Delaware', value: 48},
		{name: 'District of Columbia', value: 199},
		{name: 'Florida', value: 1627},
		{name: 'Georgia', value: 515},
		{name: 'Hawaii', value: 93},
		{name: 'Idaho', value: 33},
		{name: 'Illinois', value: 1412},
		{name: 'Indiana', value: 462},
		{name: 'Iowa', value: 70},
		{name: 'Kansas', value: 177},
		{name: 'Kentucky', value: 438},
		{name: 'Louisiana', value: 587},
		{name: 'Maine', value: 37},
		{name: 'Maryland', value: 467},
		{name: 'Massachusetts', value: 243},
		{name: 'Michigan', value: 1052},
		{name: 'Minnesota', value: 119},
		{name: 'Mississippi', value: 232},
		{name: 'Missouri', value: 567},
		{name: 'Montana', value: 30},
		{name: 'Nebraska', value: 63},
		{name: 'Nevada', value: 169},
		{name: 'New Hampshire', value: 24},
		{name: 'New Jersey', value: 573},
		{name: 'New Mexico', value: 159},
		{name: 'New York', value: 2374},
		{name: 'North Carolina', value: 687},
		{name: 'North Dakota', value: 11},
		{name: 'Ohio', value: 930},
		{name: 'Oklahoma', value: 348},
		{name: 'Oregon', value: 152},
		{name: 'Pennsylvania', value: 892},
		{name: 'Rhodes Island', value: 46},
		{name: 'South Carolina', value: 397},
		{name: 'South Dakota', value: 5},
		{name: 'Tennessee', value: 531},
		{name: 'Texas', value: 2589},
		{name: 'Utah', value: 57},
		{name: 'Vermont', value: 10},
		{name: 'Virginia', value: 491},
		{name: 'Washington', value: 245},
		{name: 'West Virginia', value: 143},
		{name: 'Wisconsin', value: 156},
		{name: 'Wyoming', value: 35},
	],
	1981:[
		{name: 'Alabama', value: 503},
		{name: 'Alaska', value: 75},
		{name: 'Arizona', value: 269},
		{name: 'Arkansas', value: 234},
		{name: 'California', value: 3144},
		{name: 'Colorado', value: 252},
		{name: 'Connecticut', value: 168},
		{name: 'Delaware', value: 47},
		{name: 'District of Columbia', value: 251},
		{name: 'Florida', value: 1734},
		{name: 'Georgia', value: 545},
		{name: 'Hawaii', value: 50},
		{name: 'Idaho', value: 48},
		{name: 'Illinois', value: 1331},
		{name: 'Indiana', value: 397},
		{name: 'Iowa', value: 95},
		{name: 'Kansas', value: 178},
		{name: 'Kentucky', value: 288},
		{name: 'Louisiana', value: 709},
		{name: 'Maine', value: 38},
		{name: 'Maryland', value: 498},
		{name: 'Massachusetts', value: 220},
		{name: 'Michigan', value: 977},
		{name: 'Minnesota', value: 93},
		{name: 'Mississippi', value: 274},
		{name: 'Missouri', value: 555},
		{name: 'Montana', value: 27},
		{name: 'Nebraska', value: 59},
		{name: 'Nevada', value: 174},
		{name: 'New Hampshire', value: 28},
		{name: 'New Jersey', value: 632},
		{name: 'New Mexico', value: 4},
		{name: 'New York', value: 2018},
		{name: 'North Carolina', value: 582},
		{name: 'North Dakota', value: 18},
		{name: 'Ohio', value: 881},
		{name: 'Oklahoma', value: 354},
		{name: 'Oregon', value: 127},
		{name: 'Pennsylvania', value: 816},
		{name: 'Rhodes Island', value: 44},
		{name: 'South Carolina', value: 369},
		{name: 'South Dakota', value: 11},
		{name: 'Tennessee', value: 463},
		{name: 'Texas', value: 2493},
		{name: 'Utah', value: 57},
		{name: 'Vermont', value: 9},
		{name: 'Virginia', value: 507},
		{name: 'Washington', value: 227},
		{name: 'West Virginia', value: 129},
		{name: 'Wisconsin', value: 167},
		{name: 'Wyoming', value: 26},
	],
	1982:[
		{name: 'Alabama', value: 452},
		{name: 'Alaska', value: 78},
		{name: 'Arizona', value: 272},
		{name: 'Arkansas', value: 214},
		{name: 'California', value: 3237},
		{name: 'Colorado', value: 213},
		{name: 'Connecticut', value: 179},
		{name: 'Delaware', value: 38},
		{name: 'District of Columbia', value: 229},
		{name: 'Florida', value: 1632},
		{name: 'Georgia', value: 637},
		{name: 'Hawaii', value: 36},
		{name: 'Idaho', value: 27},
		{name: 'Illinois', value: 1208},
		{name: 'Indiana', value: 357},
		{name: 'Iowa', value: 69},
		{name: 'Kansas', value: 160},
		{name: 'Kentucky', value: 303},
		{name: 'Louisiana', value: 720},
		{name: 'Maine', value: 26},
		{name: 'Maryland', value: 486},
		{name: 'Massachusetts', value: 235},
		{name: 'Michigan', value: 977},
		{name: 'Minnesota', value: 103},
		{name: 'Mississippi', value: 248},
		{name: 'Missouri', value: 500},
		{name: 'Montana', value: 1},
		{name: 'Nebraska', value: 37},
		{name: 'Nevada', value: 146},
		{name: 'New Hampshire', value: 25},
		{name: 'New Jersey', value: 532},
		{name: 'New Mexico', value: 124},
		{name: 'New York', value: 2138},
		{name: 'North Carolina', value: 613},
		{name: 'North Dakota', value: 6},
		{name: 'Ohio', value: 739},
		{name: 'Oklahoma', value: 408},
		{name: 'Oregon', value: 153},
		{name: 'Pennsylvania', value: 769},
		{name: 'Rhodes Island', value: 41},
		{name: 'South Carolina', value: 414},
		{name: 'South Dakota', value: 16},
		{name: 'Tennessee', value: 449},
		{name: 'Texas', value: 1983},
		{name: 'Utah', value: 62},
		{name: 'Vermont', value: 5},
		{name: 'Virginia', value: 471},
		{name: 'Washington', value: 209},
		{name: 'West Virginia', value: 119},
		{name: 'Wisconsin', value: 167},
		{name: 'Wyoming', value: 36},
	],
	1983:[
		{name: 'Alabama', value: 398},
		{name: 'Alaska', value: 79},
		{name: 'Arizona', value: 244},
		{name: 'Arkansas', value: 218},
		{name: 'California', value: 3104},
		{name: 'Colorado', value: 233},
		{name: 'Connecticut', value: 141},
		{name: 'Delaware', value: 30},
		{name: 'District of Columbia', value: 206},
		{name: 'Florida', value: 1379},
		{name: 'Georgia', value: 461},
		{name: 'Hawaii', value: 60},
		{name: 'Idaho', value: 39},
		{name: 'Illinois', value: 1214},
		{name: 'Indiana', value: 286},
		{name: 'Iowa', value: 79},
		{name: 'Kansas', value: 158},
		{name: 'Kentucky', value: 292},
		{name: 'Louisiana', value: 624},
		{name: 'Maine', value: 30},
		{name: 'Maryland', value: 413},
		{name: 'Massachusetts', value: 216},
		{name: 'Michigan', value: 991},
		{name: 'Minnesota', value: 74},
		{name: 'Mississippi', value: 215},
		{name: 'Missouri', value: 417},
		{name: 'Montana', value: 25},
		{name: 'Nebraska', value: 48},
		{name: 'Nevada', value: 127},
		{name: 'New Hampshire', value: 20},
		{name: 'New Jersey', value: 452},
		{name: 'New Mexico', value: 88},
		{name: 'New York', value: 2228},
		{name: 'North Carolina', value: 562},
		{name: 'North Dakota', value: 15},
		{name: 'Ohio', value: 631},
		{name: 'Oklahoma', value: 304},
		{name: 'Oregon', value: 122},
		{name: 'Pennsylvania', value: 654},
		{name: 'Rhodes Island', value: 32},
		{name: 'South Carolina', value: 369},
		{name: 'South Dakota', value: 12},
		{name: 'Tennessee', value: 414},
		{name: 'Texas', value: 2544},
		{name: 'Utah', value: 60},
		{name: 'Vermont', value: 7},
		{name: 'Virginia', value: 448},
		{name: 'Washington', value: 235},
		{name: 'West Virginia', value: 107},
		{name: 'Wisconsin', value: 145},
		{name: 'Wyoming', value: 32},
	],
	1984:[
		{name: 'Alabama', value: 421},
		{name: 'Alaska', value: 54},
		{name: 'Arizona', value: 264},
		{name: 'Arkansas', value: 194},
		{name: 'California', value: 3155},
		{name: 'Colorado', value: 217},
		{name: 'Connecticut', value: 128},
		{name: 'Delaware', value: 27},
		{name: 'District of Columbia', value: 196},
		{name: 'Florida', value: 1415},
		{name: 'Georgia', value: 554},
		{name: 'Hawaii', value: 38},
		{name: 'Idaho', value: 39},
		{name: 'Illinois', value: 279},
		{name: 'Indiana', value: 311},
		{name: 'Iowa', value: 60},
		{name: 'Kansas', value: 107},
		{name: 'Kentucky', value: 261},
		{name: 'Louisiana', value: 562},
		{name: 'Maine', value: 21},
		{name: 'Maryland', value: 403},
		{name: 'Massachusetts', value: 204},
		{name: 'Michigan', value: 981},
		{name: 'Minnesota', value: 77},
		{name: 'Mississippi', value: 182},
		{name: 'Missouri', value: 369},
		{name: 'Montana', value: 34},
		{name: 'Nebraska', value: 58},
		{name: 'Nevada', value: 109},
		{name: 'New Hampshire', value: 12},
		{name: 'New Jersey', value: 434},
		{name: 'New Mexico', value: 80},
		{name: 'New York', value: 1991},
		{name: 'North Carolina', value: 534},
		{name: 'North Dakota', value: 15},
		{name: 'Ohio', value: 591},
		{name: 'Oklahoma', value: 288},
		{name: 'Oregon', value: 154},
		{name: 'Pennsylvania', value: 610},
		{name: 'Rhodes Island', value: 35},
		{name: 'South Carolina', value: 356},
		{name: 'South Dakota', value: 10},
		{name: 'Tennessee', value: 358},
		{name: 'Texas', value: 2377},
		{name: 'Utah', value: 51},
		{name: 'Vermont', value: 15},
		{name: 'Virginia', value: 498},
		{name: 'Washington', value: 237},
		{name: 'West Virginia', value: 98},
		{name: 'Wisconsin', value: 131},
		{name: 'Wyoming', value: 21},
	],
	1985:[
		{name: 'Alabama', value: 435},
		{name: 'Alaska', value: 53},
		{name: 'Arizona', value: 280},
		{name: 'Arkansas', value: 207},
		{name: 'California', value: 3229},
		{name: 'Colorado', value: 223},
		{name: 'Connecticut', value: 137},
		{name: 'Delaware', value: 33},
		{name: 'District of Columbia', value: 161},
		{name: 'Florida', value: 1418},
		{name: 'Georgia', value: 602},
		{name: 'Hawaii', value: 45},
		{name: 'Idaho', value: 24},
		{name: 'Illinois', value: 252},
		{name: 'Indiana', value: 314},
		{name: 'Iowa', value: 60},
		{name: 'Kansas', value: 137},
		{name: 'Kentucky', value: 278},
		{name: 'Louisiana', value: 487},
		{name: 'Maine', value: 29},
		{name: 'Maryland', value: 385},
		{name: 'Massachusetts', value: 205},
		{name: 'Michigan', value: 1159},
		{name: 'Minnesota', value: 97},
		{name: 'Mississippi', value: 201},
		{name: 'Missouri', value: 424},
		{name: 'Montana', value: 32},
		{name: 'Nebraska', value: 54},
		{name: 'Nevada', value: 109},
		{name: 'New Hampshire', value: 19},
		{name: 'New Jersey', value: 451},
		{name: 'New Mexico', value: 153},
		{name: 'New York', value: 1709},
		{name: 'North Carolina', value: 575},
		{name: 'North Dakota', value: 7},
		{name: 'Ohio', value: 582},
		{name: 'Oklahoma', value: 312},
		{name: 'Oregon', value: 142},
		{name: 'Pennsylvania', value: 630},
		{name: 'Rhodes Island', value: 41},
		{name: 'South Carolina', value: 349},
		{name: 'South Dakota', value: 9},
		{name: 'Tennessee', value: 413},
		{name: 'Texas', value: 2429},
		{name: 'Utah', value: 57},
		{name: 'Vermont', value: 17},
		{name: 'Virginia', value: 441},
		{name: 'Washington', value: 251},
		{name: 'West Virginia', value: 79},
		{name: 'Wisconsin', value: 153},
		{name: 'Wyoming', value: 25},
	],
	1986:[
		{name: 'Alabama', value: 434},
		{name: 'Alaska', value: 53},
		{name: 'Arizona', value: 335},
		{name: 'Arkansas', value: 217},
		{name: 'California', value: 3524},
		{name: 'Colorado', value: 258},
		{name: 'Connecticut', value: 156},
		{name: 'Delaware', value: 37},
		{name: 'District of Columbia', value: 176},
		{name: 'Florida', value: 1547},
		{name: 'Georgia', value: 707},
		{name: 'Hawaii', value: 56},
		{name: 'Idaho', value: 36},
		{name: 'Illinois', value: 925},
		{name: 'Indiana', value: 280},
		{name: 'Iowa', value: 56},
		{name: 'Kansas', value: 115},
		{name: 'Kentucky', value: 271},
		{name: 'Louisiana', value: 562},
		{name: 'Maine', value: 24},
		{name: 'Maryland', value: 432},
		{name: 'Massachusetts', value: 173},
		{name: 'Michigan', value: 1157},
		{name: 'Minnesota', value: 110},
		{name: 'Mississippi', value: 189},
		{name: 'Missouri', value: 477},
		{name: 'Montana', value: 2},
		{name: 'Nebraska', value: 65},
		{name: 'Nevada', value: 118},
		{name: 'New Hampshire', value: 24},
		{name: 'New Jersey', value: 439},
		{name: 'New Mexico', value: 154},
		{name: 'New York', value: 1875},
		{name: 'North Carolina', value: 559},
		{name: 'North Dakota', value: 8},
		{name: 'Ohio', value: 593},
		{name: 'Oklahoma', value: 307},
		{name: 'Oregon', value: 195},
		{name: 'Pennsylvania', value: 618},
		{name: 'Rhodes Island', value: 37},
		{name: 'South Carolina', value: 352},
		{name: 'South Dakota', value: 23},
		{name: 'Tennessee', value: 482},
		{name: 'Texas', value: 2483},
		{name: 'Utah', value: 58},
		{name: 'Vermont', value: 13},
		{name: 'Virginia', value: 469},
		{name: 'Washington', value: 248},
		{name: 'West Virginia', value: 130},
		{name: 'Wisconsin', value: 161},
		{name: 'Wyoming', value: 31},
	],
	1987:[
		{name: 'Alabama', value: 371},
		{name: 'Alaska', value: 53},
		{name: 'Arizona', value: 291},
		{name: 'Arkansas', value: 201},
		{name: 'California', value: 3409},
		{name: 'Colorado', value: 221},
		{name: 'Connecticut', value: 172},
		{name: 'Delaware', value: 32},
		{name: 'District of Columbia', value: 242},
		{name: 'Florida', value: 1538},
		{name: 'Georgia', value: 664},
		{name: 'Hawaii', value: 58},
		{name: 'Idaho', value: 43},
		{name: 'Illinois', value: 367},
		{name: 'Indiana', value: 233},
		{name: 'Iowa', value: 31},
		{name: 'Kansas', value: 119},
		{name: 'Kentucky', value: 109},
		{name: 'Louisiana', value: 433},
		{name: 'Maine', value: 38},
		{name: 'Maryland', value: 415},
		{name: 'Massachusetts', value: 158},
		{name: 'Michigan', value: 1227},
		{name: 'Minnesota', value: 125},
		{name: 'Mississippi', value: 195},
		{name: 'Missouri', value: 421},
		{name: 'Montana', value: 0},
		{name: 'Nebraska', value: 31},
		{name: 'Nevada', value: 91},
		{name: 'New Hampshire', value: 37},
		{name: 'New Jersey', value: 393},
		{name: 'New Mexico', value: 141},
		{name: 'New York', value: 2018},
		{name: 'North Carolina', value: 568},
		{name: 'North Dakota', value: 10},
		{name: 'Ohio', value: 661},
		{name: 'Oklahoma', value: 295},
		{name: 'Oregon', value: 177},
		{name: 'Pennsylvania', value: 571},
		{name: 'Rhodes Island', value: 43},
		{name: 'South Carolina', value: 353},
		{name: 'South Dakota', value: 12},
		{name: 'Tennessee', value: 435},
		{name: 'Texas', value: 2190},
		{name: 'Utah', value: 59},
		{name: 'Vermont', value: 16},
		{name: 'Virginia', value: 490},
		{name: 'Washington', value: 272},
		{name: 'West Virginia', value: 110},
		{name: 'Wisconsin', value: 181},
		{name: 'Wyoming', value: 13},
	],
	1988:[
		{name: 'Alabama', value: 411},
		{name: 'Alaska', value: 33},
		{name: 'Arizona', value: 327},
		{name: 'Arkansas', value: 231},
		{name: 'California', value: 3394},
		{name: 'Colorado', value: 233},
		{name: 'Connecticut', value: 197},
		{name: 'Delaware', value: 37},
		{name: 'District of Columbia', value: 412},
		{name: 'Florida', value: 0},
		{name: 'Georgia', value: 797},
		{name: 'Hawaii', value: 51},
		{name: 'Idaho', value: 41},
		{name: 'Illinois', value: 1075},
		{name: 'Indiana', value: 343},
		{name: 'Iowa', value: 52},
		{name: 'Kansas', value: 42},
		{name: 'Kentucky', value: 0},
		{name: 'Louisiana', value: 483},
		{name: 'Maine', value: 36},
		{name: 'Maryland', value: 502},
		{name: 'Massachusetts', value: 162},
		{name: 'Michigan', value: 1103},
		{name: 'Minnesota', value: 132},
		{name: 'Mississippi', value: 169},
		{name: 'Missouri', value: 423},
		{name: 'Montana', value: 21},
		{name: 'Nebraska', value: 64},
		{name: 'Nevada', value: 114},
		{name: 'New Hampshire', value: 29},
		{name: 'New Jersey', value: 465},
		{name: 'New Mexico', value: 145},
		{name: 'New York', value: 2341},
		{name: 'North Carolina', value: 539},
		{name: 'North Dakota', value: 13},
		{name: 'Ohio', value: 609},
		{name: 'Oklahoma', value: 285},
		{name: 'Oregon', value: 172},
		{name: 'Pennsylvania', value: 628},
		{name: 'Rhodes Island', value: 48},
		{name: 'South Carolina', value: 383},
		{name: 'South Dakota', value: 13},
		{name: 'Tennessee', value: 439},
		{name: 'Texas', value: 2200},
		{name: 'Utah', value: 55},
		{name: 'Vermont', value: 12},
		{name: 'Virginia', value: 534},
		{name: 'Washington', value: 301},
		{name: 'West Virginia', value: 112},
		{name: 'Wisconsin', value: 161},
		{name: 'Wyoming', value: 14},
	],
	1989:[
		{name: 'Alabama', value: 452},
		{name: 'Alaska', value: 47},
		{name: 'Arizona', value: 316},
		{name: 'Arkansas', value: 238},
		{name: 'California', value: 3713},
		{name: 'Colorado', value: 182},
		{name: 'Connecticut', value: 224},
		{name: 'Delaware', value: 36},
		{name: 'District of Columbia', value: 491},
		{name: 'Florida', value: 0},
		{name: 'Georgia', value: 889},
		{name: 'Hawaii', value: 52},
		{name: 'Idaho', value: 30},
		{name: 'Illinois', value: 1164},
		{name: 'Indiana', value: 296},
		{name: 'Iowa', value: 58},
		{name: 'Kansas', value: 88},
		{name: 'Kentucky', value: 174},
		{name: 'Louisiana', value: 635},
		{name: 'Maine', value: 50},
		{name: 'Maryland', value: 602},
		{name: 'Massachusetts', value: 187},
		{name: 'Michigan', value: 1098},
		{name: 'Minnesota', value: 114},
		{name: 'Mississippi', value: 185},
		{name: 'Missouri', value: 457},
		{name: 'Montana', value: 23},
		{name: 'Nebraska', value: 46},
		{name: 'Nevada', value: 107},
		{name: 'New Hampshire', value: 45},
		{name: 'New Jersey', value: 433},
		{name: 'New Mexico', value: 113},
		{name: 'New York', value: 2112},
		{name: 'North Carolina', value: 643},
		{name: 'North Dakota', value: 3},
		{name: 'Ohio', value: 678},
		{name: 'Oklahoma', value: 262},
		{name: 'Oregon', value: 162},
		{name: 'Pennsylvania', value: 813},
		{name: 'Rhodes Island', value: 53},
		{name: 'South Carolina', value: 369},
		{name: 'South Dakota', value: 8},
		{name: 'Tennessee', value: 394},
		{name: 'Texas', value: 2314},
		{name: 'Utah', value: 49},
		{name: 'Vermont', value: 11},
		{name: 'Virginia', value: 549},
		{name: 'Washington', value: 228},
		{name: 'West Virginia', value: 132},
		{name: 'Wisconsin', value: 192},
		{name: 'Wyoming', value: 24},
	],
	1990:[
		{name: 'Alabama', value: 500},
		{name: 'Alaska', value: 40},
		{name: 'Arizona', value: 324},
		{name: 'Arkansas', value: 272},
		{name: 'California', value: 4181},
		{name: 'Colorado', value: 179},
		{name: 'Connecticut', value: 191},
		{name: 'Delaware', value: 36},
		{name: 'District of Columbia', value: 530},
		{name: 'Florida', value: 0},
		{name: 'Georgia', value: 804},
		{name: 'Hawaii', value: 52},
		{name: 'Idaho', value: 38},
		{name: 'Illinois', value: 873},
		{name: 'Indiana', value: 287},
		{name: 'Iowa', value: 57},
		{name: 'Kansas', value: 105},
		{name: 'Kentucky', value: 257},
		{name: 'Louisiana', value: 632},
		{name: 'Maine', value: 21},
		{name: 'Maryland', value: 626},
		{name: 'Massachusetts', value: 205},
		{name: 'Michigan', value: 1108},
		{name: 'Minnesota', value: 68},
		{name: 'Mississippi', value: 197},
		{name: 'Missouri', value: 473},
		{name: 'Montana', value: 1},
		{name: 'Nebraska', value: 46},
		{name: 'Nevada', value: 111},
		{name: 'New Hampshire', value: 21},
		{name: 'New Jersey', value: 478},
		{name: 'New Mexico', value: 111},
		{name: 'New York', value: 2494},
		{name: 'North Carolina', value: 764},
		{name: 'North Dakota', value: 5},
		{name: 'Ohio', value: 685},
		{name: 'Oklahoma', value: 292},
		{name: 'Oregon', value: 136},
		{name: 'Pennsylvania', value: 856},
		{name: 'Rhodes Island', value: 53},
		{name: 'South Carolina', value: 460},
		{name: 'South Dakota', value: 14},
		{name: 'Tennessee', value: 462},
		{name: 'Texas', value: 2652},
		{name: 'Utah', value: 55},
		{name: 'Vermont', value: 18},
		{name: 'Virginia', value: 611},
		{name: 'Washington', value: 267},
		{name: 'West Virginia', value: 117},
		{name: 'Wisconsin', value: 251},
		{name: 'Wyoming', value: 23},
	],
	1991:[
		{name: 'Alabama', value: 459},
		{name: 'Alaska', value: 51},
		{name: 'Arizona', value: 336},
		{name: 'Arkansas', value: 289},
		{name: 'California', value: 4455},
		{name: 'Colorado', value: 229},
		{name: 'Connecticut', value: 191},
		{name: 'Delaware', value: 43},
		{name: 'District of Columbia', value: 534},
		{name: 'Florida', value: 1},
		{name: 'Georgia', value: 805},
		{name: 'Hawaii', value: 47},
		{name: 'Idaho', value: 18},
		{name: 'Illinois', value: 1402},
		{name: 'Indiana', value: 330},
		{name: 'Iowa', value: 0},
		{name: 'Kansas', value: 171},
		{name: 'Kentucky', value: 250},
		{name: 'Louisiana', value: 358},
		{name: 'Maine', value: 0},
		{name: 'Maryland', value: 639},
		{name: 'Massachusetts', value: 234},
		{name: 'Michigan', value: 1094},
		{name: 'Minnesota', value: 122},
		{name: 'Mississippi', value: 236},
		{name: 'Missouri', value: 563},
		{name: 'Montana', value: 19},
		{name: 'Nebraska', value: 62},
		{name: 'Nevada', value: 147},
		{name: 'New Hampshire', value: 39},
		{name: 'New Jersey', value: 449},
		{name: 'New Mexico', value: 135},
		{name: 'New York', value: 2627},
		{name: 'North Carolina', value: 833},
		{name: 'North Dakota', value: 4},
		{name: 'Ohio', value: 801},
		{name: 'Oklahoma', value: 267},
		{name: 'Oregon', value: 173},
		{name: 'Pennsylvania', value: 795},
		{name: 'Rhodes Island', value: 43},
		{name: 'South Carolina', value: 424},
		{name: 'South Dakota', value: 12},
		{name: 'Tennessee', value: 436},
		{name: 'Texas', value: 2968},
		{name: 'Utah', value: 56},
		{name: 'Vermont', value: 14},
		{name: 'Virginia', value: 657},
		{name: 'Washington', value: 247},
		{name: 'West Virginia', value: 122},
		{name: 'Wisconsin', value: 269},
		{name: 'Wyoming', value: 17},
	],
	1992:[
		{name: 'Alabama', value: 391},
		{name: 'Alaska', value: 45},
		{name: 'Arizona', value: 368},
		{name: 'Arkansas', value: 277},
		{name: 'California', value: 4513},
		{name: 'Colorado', value: 248},
		{name: 'Connecticut', value: 193},
		{name: 'Delaware', value: 24},
		{name: 'District of Columbia', value: 485},
		{name: 'Florida', value: 1354},
		{name: 'Georgia', value: 751},
		{name: 'Hawaii', value: 44},
		{name: 'Idaho', value: 41},
		{name: 'Illinois', value: 1375},
		{name: 'Indiana', value: 394},
		{name: 'Iowa', value: 25},
		{name: 'Kansas', value: 174},
		{name: 'Kentucky', value: 218},
		{name: 'Louisiana', value: 742},
		{name: 'Maine', value: 0},
		{name: 'Maryland', value: 676},
		{name: 'Massachusetts', value: 190},
		{name: 'Michigan', value: 1077},
		{name: 'Minnesota', value: 146},
		{name: 'Mississippi', value: 231},
		{name: 'Missouri', value: 556},
		{name: 'Montana', value: 21},
		{name: 'Nebraska', value: 47},
		{name: 'Nevada', value: 145},
		{name: 'New Hampshire', value: 22},
		{name: 'New Jersey', value: 453},
		{name: 'New Mexico', value: 111},
		{name: 'New York', value: 2652},
		{name: 'North Carolina', value: 790},
		{name: 'North Dakota', value: 18},
		{name: 'Ohio', value: 742},
		{name: 'Oklahoma', value: 238},
		{name: 'Oregon', value: 175},
		{name: 'Pennsylvania', value: 831},
		{name: 'Rhodes Island', value: 42},
		{name: 'South Carolina', value: 407},
		{name: 'South Dakota', value: 7},
		{name: 'Tennessee', value: 507},
		{name: 'Texas', value: 2570},
		{name: 'Utah', value: 59},
		{name: 'Vermont', value: 11},
		{name: 'Virginia', value: 633},
		{name: 'Washington', value: 297},
		{name: 'West Virginia', value: 124},
		{name: 'Wisconsin', value: 235},
		{name: 'Wyoming', value: 21},
	],
	1993:[
		{name: 'Alabama', value: 523},
		{name: 'Alaska', value: 62},
		{name: 'Arizona', value: 394},
		{name: 'Arkansas', value: 288},
		{name: 'California', value: 4696},
		{name: 'Colorado', value: 240},
		{name: 'Connecticut', value: 242},
		{name: 'Delaware', value: 25},
		{name: 'District of Columbia', value: 450},
		{name: 'Florida', value: 1439},
		{name: 'Georgia', value: 828},
		{name: 'Hawaii', value: 48},
		{name: 'Idaho', value: 32},
		{name: 'Illinois', value: 1102},
		{name: 'Indiana', value: 398},
		{name: 'Iowa', value: 41},
		{name: 'Kansas', value: 32},
		{name: 'Kentucky', value: 256},
		{name: 'Louisiana', value: 861},
		{name: 'Maine', value: 8},
		{name: 'Maryland', value: 716},
		{name: 'Massachusetts', value: 230},
		{name: 'Michigan', value: 1072},
		{name: 'Minnesota', value: 154},
		{name: 'Mississippi', value: 250},
		{name: 'Missouri', value: 596},
		{name: 'Montana', value: 0},
		{name: 'Nebraska', value: 32},
		{name: 'Nevada', value: 152},
		{name: 'New Hampshire', value: 22},
		{name: 'New Jersey', value: 462},
		{name: 'New Mexico', value: 110},
		{name: 'New York', value: 2736},
		{name: 'North Carolina', value: 862},
		{name: 'North Dakota', value: 11},
		{name: 'Ohio', value: 689},
		{name: 'Oklahoma', value: 328},
		{name: 'Oregon', value: 169},
		{name: 'Pennsylvania', value: 912},
		{name: 'Rhodes Island', value: 41},
		{name: 'South Carolina', value: 434},
		{name: 'South Dakota', value: 24},
		{name: 'Tennessee', value: 515},
		{name: 'Texas', value: 2450},
		{name: 'Utah', value: 72},
		{name: 'Vermont', value: 13},
		{name: 'Virginia', value: 613},
		{name: 'Washington', value: 302},
		{name: 'West Virginia', value: 137},
		{name: 'Wisconsin', value: 259},
		{name: 'Wyoming', value: 19},
	],
	1994:[
		{name: 'Alabama', value: 548},
		{name: 'Alaska', value: 46},
		{name: 'Arizona', value: 467},
		{name: 'Arkansas', value: 323},
		{name: 'California', value: 4295},
		{name: 'Colorado', value: 203},
		{name: 'Connecticut', value: 235},
		{name: 'Delaware', value: 16},
		{name: 'District of Columbia', value: 453},
		{name: 'Florida', value: 1375},
		{name: 'Georgia', value: 746},
		{name: 'Hawaii', value: 53},
		{name: 'Idaho', value: 45},
		{name: 'Illinois', value: 1313},
		{name: 'Indiana', value: 424},
		{name: 'Iowa', value: 49},
		{name: 'Kansas', value: 0},
		{name: 'Kentucky', value: 93},
		{name: 'Louisiana', value: 929},
		{name: 'Maine', value: 34},
		{name: 'Maryland', value: 659},
		{name: 'Massachusetts', value: 218},
		{name: 'Michigan', value: 1032},
		{name: 'Minnesota', value: 156},
		{name: 'Mississippi', value: 252},
		{name: 'Missouri', value: 593},
		{name: 'Montana', value: 0},
		{name: 'Nebraska', value: 20},
		{name: 'Nevada', value: 193},
		{name: 'New Hampshire', value: 17},
		{name: 'New Jersey', value: 437},
		{name: 'New Mexico', value: 128},
		{name: 'New York', value: 2243},
		{name: 'North Carolina', value: 869},
		{name: 'North Dakota', value: 1},
		{name: 'Ohio', value: 678},
		{name: 'Oklahoma', value: 277},
		{name: 'Oregon', value: 195},
		{name: 'Pennsylvania', value: 797},
		{name: 'Rhodes Island', value: 46},
		{name: 'South Carolina', value: 402},
		{name: 'South Dakota', value: 9},
		{name: 'Tennessee', value: 490},
		{name: 'Texas', value: 2298},
		{name: 'Utah', value: 74},
		{name: 'Vermont', value: 7},
		{name: 'Virginia', value: 657},
		{name: 'Washington', value: 345},
		{name: 'West Virginia', value: 113},
		{name: 'Wisconsin', value: 268},
		{name: 'Wyoming', value: 20},
	],
	1995:[
		{name: 'Alabama', value: 506},
		{name: 'Alaska', value: 59},
		{name: 'Arizona', value: 527},
		{name: 'Arkansas', value: 296},
		{name: 'California', value: 4052},
		{name: 'Colorado', value: 240},
		{name: 'Connecticut', value: 162},
		{name: 'Delaware', value: 9},
		{name: 'District of Columbia', value: 408},
		{name: 'Florida', value: 1214},
		{name: 'Georgia', value: 720},
		{name: 'Hawaii', value: 61},
		{name: 'Idaho', value: 52},
		{name: 'Illinois', value: 884},
		{name: 'Indiana', value: 413},
		{name: 'Iowa', value: 61},
		{name: 'Kansas', value: 0},
		{name: 'Kentucky', value: 277},
		{name: 'Louisiana', value: 820},
		{name: 'Maine', value: 30},
		{name: 'Maryland', value: 683},
		{name: 'Massachusetts', value: 235},
		{name: 'Michigan', value: 902},
		{name: 'Minnesota', value: 193},
		{name: 'Mississippi', value: 224},
		{name: 'Missouri', value: 482},
		{name: 'Montana', value: 19},
		{name: 'Nebraska', value: 23},
		{name: 'Nevada', value: 189},
		{name: 'New Hampshire', value: 19},
		{name: 'New Jersey', value: 467},
		{name: 'New Mexico', value: 127},
		{name: 'New York', value: 1751},
		{name: 'North Carolina', value: 777},
		{name: 'North Dakota', value: 5},
		{name: 'Ohio', value: 593},
		{name: 'Oklahoma', value: 419},
		{name: 'Oregon', value: 160},
		{name: 'Pennsylvania', value: 786},
		{name: 'Rhodes Island', value: 35},
		{name: 'South Carolina', value: 327},
		{name: 'South Dakota', value: 13},
		{name: 'Tennessee', value: 527},
		{name: 'Texas', value: 1886},
		{name: 'Utah', value: 82},
		{name: 'Vermont', value: 14},
		{name: 'Virginia', value: 559},
		{name: 'Washington', value: 301},
		{name: 'West Virginia', value: 100},
		{name: 'Wisconsin', value: 250},
		{name: 'Wyoming', value: 13},
	],
	1996:[
		{name: 'Alabama', value: 463},
		{name: 'Alaska', value: 44},
		{name: 'Arizona', value: 421},
		{name: 'Arkansas', value: 240},
		{name: 'California', value: 3413},
		{name: 'Colorado', value: 198},
		{name: 'Connecticut', value: 178},
		{name: 'Delaware', value: 40},
		{name: 'District of Columbia', value: 0},
		{name: 'Florida', value: 1531},
		{name: 'Georgia', value: 702},
		{name: 'Hawaii', value: 44},
		{name: 'Idaho', value: 55},
		{name: 'Illinois', value: 867},
		{name: 'Indiana', value: 342},
		{name: 'Iowa', value: 62},
		{name: 'Kansas', value: 0},
		{name: 'Kentucky', value: 250},
		{name: 'Louisiana', value: 813},
		{name: 'Maine', value: 29},
		{name: 'Maryland', value: 638},
		{name: 'Massachusetts', value: 180},
		{name: 'Michigan', value: 780},
		{name: 'Minnesota', value: 173},
		{name: 'Mississippi', value: 215},
		{name: 'Missouri', value: 435},
		{name: 'Montana', value: 0},
		{name: 'Nebraska', value: 22},
		{name: 'Nevada', value: 244},
		{name: 'New Hampshire', value: 22},
		{name: 'New Jersey', value: 377},
		{name: 'New Mexico', value: 158},
		{name: 'New York', value: 1464},
		{name: 'North Carolina', value: 700},
		{name: 'North Dakota', value: 14},
		{name: 'Ohio', value: 544},
		{name: 'Oklahoma', value: 249},
		{name: 'Oregon', value: 152},
		{name: 'Pennsylvania', value: 764},
		{name: 'Rhodes Island', value: 25},
		{name: 'South Carolina', value: 376},
		{name: 'South Dakota', value: 8},
		{name: 'Tennessee', value: 460},
		{name: 'Texas', value: 1688},
		{name: 'Utah', value: 72},
		{name: 'Vermont', value: 16},
		{name: 'Virginia', value: 554},
		{name: 'Washington', value: 282},
		{name: 'West Virginia', value: 77},
		{name: 'Wisconsin', value: 240},
		{name: 'Wyoming', value: 19},
	],
	1997:[
		{name: 'Alabama', value: 455},
		{name: 'Alaska', value: 61},
		{name: 'Arizona', value: 435},
		{name: 'Arkansas', value: 284},
		{name: 'California', value: 2993},
		{name: 'Colorado', value: 186},
		{name: 'Connecticut', value: 144},
		{name: 'Delaware', value: 17},
		{name: 'District of Columbia', value: 334},
		{name: 'Florida', value: 1159},
		{name: 'Georgia', value: 577},
		{name: 'Hawaii', value: 52},
		{name: 'Idaho', value: 45},
		{name: 'Illinois', value: 825},
		{name: 'Indiana', value: 435},
		{name: 'Iowa', value: 52},
		{name: 'Kansas', value: 0},
		{name: 'Kentucky', value: 242},
		{name: 'Louisiana', value: 739},
		{name: 'Maine', value: 23},
		{name: 'Maryland', value: 581},
		{name: 'Massachusetts', value: 134},
		{name: 'Michigan', value: 813},
		{name: 'Minnesota', value: 136},
		{name: 'Mississippi', value: 210},
		{name: 'Missouri', value: 434},
		{name: 'Montana', value: 16},
		{name: 'Nebraska', value: 24},
		{name: 'Nevada', value: 211},
		{name: 'New Hampshire', value: 0},
		{name: 'New Jersey', value: 384},
		{name: 'New Mexico', value: 124},
		{name: 'New York', value: 1214},
		{name: 'North Carolina', value: 714},
		{name: 'North Dakota', value: 7},
		{name: 'Ohio', value: 416},
		{name: 'Oklahoma', value: 271},
		{name: 'Oregon', value: 125},
		{name: 'Pennsylvania', value: 806},
		{name: 'Rhodes Island', value: 29},
		{name: 'South Carolina', value: 349},
		{name: 'South Dakota', value: 7},
		{name: 'Tennessee', value: 475},
		{name: 'Texas', value: 1547},
		{name: 'Utah', value: 81},
		{name: 'Vermont', value: 9},
		{name: 'Virginia', value: 554},
		{name: 'Washington', value: 279},
		{name: 'West Virginia', value: 89},
		{name: 'Wisconsin', value: 245},
		{name: 'Wyoming', value: 22},
	],
	1998:[
		{name: 'Alabama', value: 379},
		{name: 'Alaska', value: 43},
		{name: 'Arizona', value: 423},
		{name: 'Arkansas', value: 227},
		{name: 'California', value: 2575},
		{name: 'Colorado', value: 206},
		{name: 'Connecticut', value: 164},
		{name: 'Delaware', value: 25},
		{name: 'District of Columbia', value: 0},
		{name: 'Florida', value: 1199},
		{name: 'Georgia', value: 581},
		{name: 'Hawaii', value: 31},
		{name: 'Idaho', value: 42},
		{name: 'Illinois', value: 795},
		{name: 'Indiana', value: 442},
		{name: 'Iowa', value: 55},
		{name: 'Kansas', value: 0},
		{name: 'Kentucky', value: 133},
		{name: 'Louisiana', value: 634},
		{name: 'Maine', value: 28},
		{name: 'Maryland', value: 578},
		{name: 'Massachusetts', value: 135},
		{name: 'Michigan', value: 785},
		{name: 'Minnesota', value: 129},
		{name: 'Mississippi', value: 203},
		{name: 'Missouri', value: 409},
		{name: 'Montana', value: 13},
		{name: 'Nebraska', value: 27},
		{name: 'Nevada', value: 197},
		{name: 'New Hampshire', value: 19},
		{name: 'New Jersey', value: 363},
		{name: 'New Mexico', value: 174},
		{name: 'New York', value: 1005},
		{name: 'North Carolina', value: 686},
		{name: 'North Dakota', value: 7},
		{name: 'Ohio', value: 411},
		{name: 'Oklahoma', value: 243},
		{name: 'Oregon', value: 146},
		{name: 'Pennsylvania', value: 691},
		{name: 'Rhodes Island', value: 28},
		{name: 'South Carolina', value: 344},
		{name: 'South Dakota', value: 7},
		{name: 'Tennessee', value: 484},
		{name: 'Texas', value: 1587},
		{name: 'Utah', value: 74},
		{name: 'Vermont', value: 12},
		{name: 'Virginia', value: 462},
		{name: 'Washington', value: 237},
		{name: 'West Virginia', value: 87},
		{name: 'Wisconsin', value: 0},
		{name: 'Wyoming', value: 17},
	],
	1999:[
		{name: 'Alabama', value: 17},
		{name: 'Alaska', value: 62},
		{name: 'Arizona', value: 460},
		{name: 'Arkansas', value: 162},
		{name: 'California', value: 2315},
		{name: 'Colorado', value: 214},
		{name: 'Connecticut', value: 134},
		{name: 'Delaware', value: 26},
		{name: 'District of Columbia', value: 0},
		{name: 'Florida', value: 992},
		{name: 'Georgia', value: 568},
		{name: 'Hawaii', value: 44},
		{name: 'Idaho', value: 28},
		{name: 'Illinois', value: 722},
		{name: 'Indiana', value: 371},
		{name: 'Iowa', value: 57},
		{name: 'Kansas', value: 0},
		{name: 'Kentucky', value: 92},
		{name: 'Louisiana', value: 527},
		{name: 'Maine', value: 28},
		{name: 'Maryland', value: 492},
		{name: 'Massachusetts', value: 127},
		{name: 'Michigan', value: 797},
		{name: 'Minnesota', value: 143},
		{name: 'Mississippi', value: 166},
		{name: 'Missouri', value: 364},
		{name: 'Montana', value: 11},
		{name: 'Nebraska', value: 28},
		{name: 'Nevada', value: 182},
		{name: 'New Hampshire', value: 25},
		{name: 'New Jersey', value: 321},
		{name: 'New Mexico', value: 153},
		{name: 'New York', value: 998},
		{name: 'North Carolina', value: 619},
		{name: 'North Dakota', value: 8},
		{name: 'Ohio', value: 404},
		{name: 'Oklahoma', value: 286},
		{name: 'Oregon', value: 101},
		{name: 'Pennsylvania', value: 657},
		{name: 'Rhodes Island', value: 38},
		{name: 'South Carolina', value: 308},
		{name: 'South Dakota', value: 14},
		{name: 'Tennessee', value: 447},
		{name: 'Texas', value: 1404},
		{name: 'Utah', value: 65},
		{name: 'Vermont', value: 20},
		{name: 'Virginia', value: 410},
		{name: 'Washington', value: 195},
		{name: 'West Virginia', value: 72},
		{name: 'Wisconsin', value: 219},
		{name: 'Wyoming', value: 13},
	],
	2000:[
		{name: 'Alabama', value: 236},
		{name: 'Alaska', value: 41},
		{name: 'Arizona', value: 411},
		{name: 'Arkansas', value: 182},
		{name: 'California', value: 2402},
		{name: 'Colorado', value: 146},
		{name: 'Connecticut', value: 110},
		{name: 'Delaware', value: 30},
		{name: 'District of Columbia', value: 0},
		{name: 'Florida', value: 899},
		{name: 'Georgia', value: 572},
		{name: 'Hawaii', value: 36},
		{name: 'Idaho', value: 18},
		{name: 'Illinois', value: 695},
		{name: 'Indiana', value: 331},
		{name: 'Iowa', value: 58},
		{name: 'Kansas', value: 51},
		{name: 'Kentucky', value: 76},
		{name: 'Louisiana', value: 607},
		{name: 'Maine', value: 16},
		{name: 'Maryland', value: 507},
		{name: 'Massachusetts', value: 132},
		{name: 'Michigan', value: 761},
		{name: 'Minnesota', value: 121},
		{name: 'Mississippi', value: 189},
		{name: 'Missouri', value: 372},
		{name: 'Montana', value: 14},
		{name: 'Nebraska', value: 35},
		{name: 'Nevada', value: 148},
		{name: 'New Hampshire', value: 16},
		{name: 'New Jersey', value: 311},
		{name: 'New Mexico', value: 139},
		{name: 'New York', value: 1032},
		{name: 'North Carolina', value: 619},
		{name: 'North Dakota', value: 4},
		{name: 'Ohio', value: 398},
		{name: 'Oklahoma', value: 217},
		{name: 'Oregon', value: 75},
		{name: 'Pennsylvania', value: 665},
		{name: 'Rhodes Island', value: 45},
		{name: 'South Carolina', value: 305},
		{name: 'South Dakota', value: 8},
		{name: 'Tennessee', value: 474},
		{name: 'Texas', value: 1419},
		{name: 'Utah', value: 62},
		{name: 'Vermont', value: 10},
		{name: 'Virginia', value: 428},
		{name: 'Washington', value: 218},
		{name: 'West Virginia', value: 68},
		{name: 'Wisconsin', value: 187},
		{name: 'Wyoming', value: 13},
	],
	2001:[
		{name: 'Alabama', value: 377},
		{name: 'Alaska', value: 43},
		{name: 'Arizona', value: 478},
		{name: 'Arkansas', value: 162},
		{name: 'California', value: 2537},
		{name: 'Colorado', value: 170},
		{name: 'Connecticut', value: 117},
		{name: 'Delaware', value: 30},
		{name: 'District of Columbia', value: 1},
		{name: 'Florida', value: 1011},
		{name: 'Georgia', value: 645},
		{name: 'Hawaii', value: 42},
		{name: 'Idaho', value: 36},
		{name: 'Illinois', value: 730},
		{name: 'Indiana', value: 411},
		{name: 'Iowa', value: 57},
		{name: 'Kansas', value: 87},
		{name: 'Kentucky', value: 88},
		{name: 'Louisiana', value: 549},
		{name: 'Maine', value: 24},
		{name: 'Maryland', value: 525},
		{name: 'Massachusetts', value: 164},
		{name: 'Michigan', value: 725},
		{name: 'Minnesota', value: 127},
		{name: 'Mississippi', value: 209},
		{name: 'Missouri', value: 425},
		{name: 'Montana', value: 26},
		{name: 'Nebraska', value: 20},
		{name: 'Nevada', value: 220},
		{name: 'New Hampshire', value: 22},
		{name: 'New Jersey', value: 388},
		{name: 'New Mexico', value: 108},
		{name: 'New York', value: 1025},
		{name: 'North Carolina', value: 581},
		{name: 'North Dakota', value: 9},
		{name: 'Ohio', value: 489},
		{name: 'Oklahoma', value: 230},
		{name: 'Oregon', value: 108},
		{name: 'Pennsylvania', value: 710},
		{name: 'Rhodes Island', value: 40},
		{name: 'South Carolina', value: 362},
		{name: 'South Dakota', value: 10},
		{name: 'Tennessee', value: 476},
		{name: 'Texas', value: 1497},
		{name: 'Utah', value: 92},
		{name: 'Vermont', value: 7},
		{name: 'Virginia', value: 408},
		{name: 'Washington', value: 216},
		{name: 'West Virginia', value: 41},
		{name: 'Wisconsin', value: 220},
		{name: 'Wyoming', value: 11},
	],
	2002:[
		{name: 'Alabama', value: 318},
		{name: 'Alaska', value: 42},
		{name: 'Arizona', value: 476},
		{name: 'Arkansas', value: 156},
		{name: 'California', value: 2766},
		{name: 'Colorado', value: 197},
		{name: 'Connecticut', value: 94},
		{name: 'Delaware', value: 30},
		{name: 'District of Columbia', value: 269},
		{name: 'Florida', value: 1039},
		{name: 'Georgia', value: 636},
		{name: 'Hawaii', value: 27},
		{name: 'Idaho', value: 39},
		{name: 'Illinois', value: 714},
		{name: 'Indiana', value: 356},
		{name: 'Iowa', value: 56},
		{name: 'Kansas', value: 78},
		{name: 'Kentucky', value: 95},
		{name: 'Louisiana', value: 628},
		{name: 'Maine', value: 16},
		{name: 'Maryland', value: 590},
		{name: 'Massachusetts', value: 186},
		{name: 'Michigan', value: 750},
		{name: 'Minnesota', value: 125},
		{name: 'Mississippi', value: 214},
		{name: 'Missouri', value: 389},
		{name: 'Montana', value: 16},
		{name: 'Nebraska', value: 25},
		{name: 'Nevada', value: 204},
		{name: 'New Hampshire', value: 15},
		{name: 'New Jersey', value: 377},
		{name: 'New Mexico', value: 160},
		{name: 'New York', value: 968},
		{name: 'North Carolina', value: 619},
		{name: 'North Dakota', value: 7},
		{name: 'Ohio', value: 559},
		{name: 'Oklahoma', value: 201},
		{name: 'Oregon', value: 82},
		{name: 'Pennsylvania', value: 678},
		{name: 'Rhodes Island', value: 41},
		{name: 'South Carolina', value: 336},
		{name: 'South Dakota', value: 14},
		{name: 'Tennessee', value: 490},
		{name: 'Texas', value: 1510},
		{name: 'Utah', value: 63},
		{name: 'Vermont', value: 13},
		{name: 'Virginia', value: 432},
		{name: 'Washington', value: 222},
		{name: 'West Virginia', value: 80},
		{name: 'Wisconsin', value: 177},
		{name: 'Wyoming', value: 18},
	],
	2003:[
		{name: 'Alabama', value: 314},
		{name: 'Alaska', value: 50},
		{name: 'Arizona', value: 519},
		{name: 'Arkansas', value: 171},
		{name: 'California', value: 2794},
		{name: 'Colorado', value: 203},
		{name: 'Connecticut', value: 114},
		{name: 'Delaware', value: 23},
		{name: 'District of Columbia', value: 258},
		{name: 'Florida', value: 1060},
		{name: 'Georgia', value: 699},
		{name: 'Hawaii', value: 24},
		{name: 'Idaho', value: 32},
		{name: 'Illinois', value: 665},
		{name: 'Indiana', value: 353},
		{name: 'Iowa', value: 61},
		{name: 'Kansas', value: 103},
		{name: 'Kentucky', value: 87},
		{name: 'Louisiana', value: 649},
		{name: 'Maine', value: 19},
		{name: 'Maryland', value: 587},
		{name: 'Massachusetts', value: 151},
		{name: 'Michigan', value: 684},
		{name: 'Minnesota', value: 132},
		{name: 'Mississippi', value: 203},
		{name: 'Missouri', value: 346},
		{name: 'Montana', value: 23},
		{name: 'Nebraska', value: 21},
		{name: 'Nevada', value: 212},
		{name: 'New Hampshire', value: 11},
		{name: 'New Jersey', value: 462},
		{name: 'New Mexico', value: 126},
		{name: 'New York', value: 973},
		{name: 'North Carolina', value: 565},
		{name: 'North Dakota', value: 8},
		{name: 'Ohio', value: 533},
		{name: 'Oklahoma', value: 247},
		{name: 'Oregon', value: 86},
		{name: 'Pennsylvania', value: 718},
		{name: 'Rhodes Island', value: 25},
		{name: 'South Carolina', value: 332},
		{name: 'South Dakota', value: 11},
		{name: 'Tennessee', value: 458},
		{name: 'Texas', value: 1612},
		{name: 'Utah', value: 64},
		{name: 'Vermont', value: 16},
		{name: 'Virginia', value: 454},
		{name: 'Washington', value: 223},
		{name: 'West Virginia', value: 73},
		{name: 'Wisconsin', value: 205},
		{name: 'Wyoming', value: 20},
	],
	2004:[
		{name: 'Alabama', value: 274},
		{name: 'Alaska', value: 45},
		{name: 'Arizona', value: 502},
		{name: 'Arkansas', value: 169},
		{name: 'California', value: 2782},
		{name: 'Colorado', value: 230},
		{name: 'Connecticut', value: 113},
		{name: 'Delaware', value: 29},
		{name: 'District of Columbia', value: 212},
		{name: 'Florida', value: 1093},
		{name: 'Georgia', value: 585},
		{name: 'Hawaii', value: 38},
		{name: 'Idaho', value: 34},
		{name: 'Illinois', value: 503},
		{name: 'Indiana', value: 337},
		{name: 'Iowa', value: 54},
		{name: 'Kansas', value: 85},
		{name: 'Kentucky', value: 234},
		{name: 'Louisiana', value: 623},
		{name: 'Maine', value: 18},
		{name: 'Maryland', value: 578},
		{name: 'Massachusetts', value: 188},
		{name: 'Michigan', value: 713},
		{name: 'Minnesota', value: 129},
		{name: 'Mississippi', value: 194},
		{name: 'Missouri', value: 404},
		{name: 'Montana', value: 31},
		{name: 'Nebraska', value: 31},
		{name: 'Nevada', value: 198},
		{name: 'New Hampshire', value: 15},
		{name: 'New Jersey', value: 448},
		{name: 'New Mexico', value: 171},
		{name: 'New York', value: 970},
		{name: 'North Carolina', value: 552},
		{name: 'North Dakota', value: 9},
		{name: 'Ohio', value: 548},
		{name: 'Oklahoma', value: 225},
		{name: 'Oregon', value: 117},
		{name: 'Pennsylvania', value: 764},
		{name: 'Rhodes Island', value: 30},
		{name: 'South Carolina', value: 316},
		{name: 'South Dakota', value: 16},
		{name: 'Tennessee', value: 411},
		{name: 'Texas', value: 1543},
		{name: 'Utah', value: 63},
		{name: 'Vermont', value: 17},
		{name: 'Virginia', value: 428},
		{name: 'Washington', value: 223},
		{name: 'West Virginia', value: 72},
		{name: 'Wisconsin', value: 168},
		{name: 'Wyoming', value: 14},
	],
	2005:[
		{name: 'Alabama', value: 361},
		{name: 'Alaska', value: 41},
		{name: 'Arizona', value: 509},
		{name: 'Arkansas', value: 194},
		{name: 'California', value: 2886},
		{name: 'Colorado', value: 191},
		{name: 'Connecticut', value: 115},
		{name: 'Delaware', value: 43},
		{name: 'District of Columbia', value: 203},
		{name: 'Florida', value: 1038},
		{name: 'Georgia', value: 567},
		{name: 'Hawaii', value: 27},
		{name: 'Idaho', value: 50},
		{name: 'Illinois', value: 492},
		{name: 'Indiana', value: 369},
		{name: 'Iowa', value: 44},
		{name: 'Kansas', value: 109},
		{name: 'Kentucky', value: 190},
		{name: 'Louisiana', value: 469},
		{name: 'Maine', value: 23},
		{name: 'Maryland', value: 635},
		{name: 'Massachusetts', value: 190},
		{name: 'Michigan', value: 705},
		{name: 'Minnesota', value: 128},
		{name: 'Mississippi', value: 173},
		{name: 'Missouri', value: 457},
		{name: 'Montana', value: 24},
		{name: 'Nebraska', value: 15},
		{name: 'Nevada', value: 243},
		{name: 'New Hampshire', value: 20},
		{name: 'New Jersey', value: 457},
		{name: 'New Mexico', value: 145},
		{name: 'New York', value: 960},
		{name: 'North Carolina', value: 645},
		{name: 'North Dakota', value: 11},
		{name: 'Ohio', value: 616},
		{name: 'Oklahoma', value: 220},
		{name: 'Oregon', value: 104},
		{name: 'Pennsylvania', value: 839},
		{name: 'Rhodes Island', value: 34},
		{name: 'South Carolina', value: 343},
		{name: 'South Dakota', value: 17},
		{name: 'Tennessee', value: 489},
		{name: 'Texas', value: 1593},
		{name: 'Utah', value: 63},
		{name: 'Vermont', value: 10},
		{name: 'Virginia', value: 497},
		{name: 'Washington', value: 243},
		{name: 'West Virginia', value: 84},
		{name: 'Wisconsin', value: 231},
		{name: 'Wyoming', value: 18},
	],
	2006:[
		{name: 'Alabama', value: 391},
		{name: 'Alaska', value: 43},
		{name: 'Arizona', value: 548},
		{name: 'Arkansas', value: 231},
		{name: 'California', value: 2868},
		{name: 'Colorado', value: 186},
		{name: 'Connecticut', value: 124},
		{name: 'Delaware', value: 43},
		{name: 'District of Columbia', value: 182},
		{name: 'Florida', value: 1311},
		{name: 'Georgia', value: 647},
		{name: 'Hawaii', value: 23},
		{name: 'Idaho', value: 36},
		{name: 'Illinois', value: 536},
		{name: 'Indiana', value: 378},
		{name: 'Iowa', value: 57},
		{name: 'Kansas', value: 138},
		{name: 'Kentucky', value: 174},
		{name: 'Louisiana', value: 548},
		{name: 'Maine', value: 28},
		{name: 'Maryland', value: 622},
		{name: 'Massachusetts', value: 204},
		{name: 'Michigan', value: 797},
		{name: 'Minnesota', value: 131},
		{name: 'Mississippi', value: 193},
		{name: 'Missouri', value: 392},
		{name: 'Montana', value: 22},
		{name: 'Nebraska', value: 18},
		{name: 'Nevada', value: 261},
		{name: 'New Hampshire', value: 14},
		{name: 'New Jersey', value: 474},
		{name: 'New Mexico', value: 122},
		{name: 'New York', value: 1017},
		{name: 'North Carolina', value: 619},
		{name: 'North Dakota', value: 7},
		{name: 'Ohio', value: 571},
		{name: 'Oklahoma', value: 242},
		{name: 'Oregon', value: 117},
		{name: 'Pennsylvania', value: 850},
		{name: 'Rhodes Island', value: 28},
		{name: 'South Carolina', value: 401},
		{name: 'South Dakota', value: 11},
		{name: 'Tennessee', value: 480},
		{name: 'Texas', value: 1585},
		{name: 'Utah', value: 57},
		{name: 'Vermont', value: 15},
		{name: 'Virginia', value: 447},
		{name: 'Washington', value: 223},
		{name: 'West Virginia', value: 80},
		{name: 'Wisconsin', value: 187},
		{name: 'Wyoming', value: 10},
	],
	2007:[
		{name: 'Alabama', value: 417},
		{name: 'Alaska', value: 59},
		{name: 'Arizona', value: 556},
		{name: 'Arkansas', value: 205},
		{name: 'California', value: 2645},
		{name: 'Colorado', value: 169},
		{name: 'Connecticut', value: 118},
		{name: 'Delaware', value: 42},
		{name: 'District of Columbia', value: 190},
		{name: 'Florida', value: 1474},
		{name: 'Georgia', value: 740},
		{name: 'Hawaii', value: 27},
		{name: 'Idaho', value: 56},
		{name: 'Illinois', value: 514},
		{name: 'Indiana', value: 375},
		{name: 'Iowa', value: 48},
		{name: 'Kansas', value: 116},
		{name: 'Kentucky', value: 229},
		{name: 'Louisiana', value: 658},
		{name: 'Maine', value: 28},
		{name: 'Maryland', value: 638},
		{name: 'Massachusetts', value: 201},
		{name: 'Michigan', value: 731},
		{name: 'Minnesota', value: 124},
		{name: 'Mississippi', value: 161},
		{name: 'Missouri', value: 419},
		{name: 'Montana', value: 16},
		{name: 'Nebraska', value: 26},
		{name: 'Nevada', value: 228},
		{name: 'New Hampshire', value: 14},
		{name: 'New Jersey', value: 423},
		{name: 'New Mexico', value: 179},
		{name: 'New York', value: 860},
		{name: 'North Carolina', value: 622},
		{name: 'North Dakota', value: 14},
		{name: 'Ohio', value: 550},
		{name: 'Oklahoma', value: 276},
		{name: 'Oregon', value: 86},
		{name: 'Pennsylvania', value: 866},
		{name: 'Rhodes Island', value: 20},
		{name: 'South Carolina', value: 403},
		{name: 'South Dakota', value: 17},
		{name: 'Tennessee', value: 486},
		{name: 'Texas', value: 1654},
		{name: 'Utah', value: 71},
		{name: 'Vermont', value: 14},
		{name: 'Virginia', value: 453},
		{name: 'Washington', value: 201},
		{name: 'West Virginia', value: 68},
		{name: 'Wisconsin', value: 215},
		{name: 'Wyoming', value: 19},
	],
	2008:[
		{name: 'Alabama', value: 371},
		{name: 'Alaska', value: 31},
		{name: 'Arizona', value: 442},
		{name: 'Arkansas', value: 172},
		{name: 'California', value: 2315},
		{name: 'Colorado', value: 171},
		{name: 'Connecticut', value: 143},
		{name: 'Delaware', value: 65},
		{name: 'District of Columbia', value: 0},
		{name: 'Florida', value: 1396},
		{name: 'Georgia', value: 665},
		{name: 'Hawaii', value: 29},
		{name: 'Idaho', value: 24},
		{name: 'Illinois', value: 567},
		{name: 'Indiana', value: 332},
		{name: 'Iowa', value: 83},
		{name: 'Kansas', value: 117},
		{name: 'Kentucky', value: 208},
		{name: 'Louisiana', value: 429},
		{name: 'Maine', value: 33},
		{name: 'Maryland', value: 526},
		{name: 'Massachusetts', value: 183},
		{name: 'Michigan', value: 590},
		{name: 'Minnesota', value: 112},
		{name: 'Mississippi', value: 195},
		{name: 'Missouri', value: 482},
		{name: 'Montana', value: 30},
		{name: 'Nebraska', value: 25},
		{name: 'Nevada', value: 171},
		{name: 'New Hampshire', value: 14},
		{name: 'New Jersey', value: 411},
		{name: 'New Mexico', value: 145},
		{name: 'New York', value: 906},
		{name: 'North Carolina', value: 647},
		{name: 'North Dakota', value: 3},
		{name: 'Ohio', value: 508},
		{name: 'Oklahoma', value: 226},
		{name: 'Oregon', value: 90},
		{name: 'Pennsylvania', value: 771},
		{name: 'Rhodes Island', value: 32},
		{name: 'South Carolina', value: 332},
		{name: 'South Dakota', value: 25},
		{name: 'Tennessee', value: 446},
		{name: 'Texas', value: 1463},
		{name: 'Utah', value: 43},
		{name: 'Vermont', value: 17},
		{name: 'Virginia', value: 403},
		{name: 'Washington', value: 205},
		{name: 'West Virginia', value: 66},
		{name: 'Wisconsin', value: 158},
		{name: 'Wyoming', value: 11},
	],
	2009:[
		{name: 'Alabama', value: 345},
		{name: 'Alaska', value: 40},
		{name: 'Arizona', value: 395},
		{name: 'Arkansas', value: 194},
		{name: 'California', value: 2319},
		{name: 'Colorado', value: 180},
		{name: 'Connecticut', value: 114},
		{name: 'Delaware', value: 47},
		{name: 'District of Columbia', value: 170},
		{name: 'Florida', value: 1245},
		{name: 'Georgia', value: 639},
		{name: 'Hawaii', value: 27},
		{name: 'Idaho', value: 23},
		{name: 'Illinois', value: 527},
		{name: 'Indiana', value: 326},
		{name: 'Iowa', value: 46},
		{name: 'Kansas', value: 136},
		{name: 'Kentucky', value: 206},
		{name: 'Louisiana', value: 559},
		{name: 'Maine', value: 28},
		{name: 'Maryland', value: 512},
		{name: 'Massachusetts', value: 189},
		{name: 'Michigan', value: 697},
		{name: 'Minnesota', value: 97},
		{name: 'Mississippi', value: 175},
		{name: 'Missouri', value: 440},
		{name: 'Montana', value: 31},
		{name: 'Nebraska', value: 52},
		{name: 'Nevada', value: 203},
		{name: 'New Hampshire', value: 11},
		{name: 'New Jersey', value: 362},
		{name: 'New Mexico', value: 170},
		{name: 'New York', value: 835},
		{name: 'North Carolina', value: 550},
		{name: 'North Dakota', value: 9},
		{name: 'Ohio', value: 571},
		{name: 'Oklahoma', value: 273},
		{name: 'Oregon', value: 107},
		{name: 'Pennsylvania', value: 793},
		{name: 'Rhodes Island', value: 33},
		{name: 'South Carolina', value: 345},
		{name: 'South Dakota', value: 22},
		{name: 'Tennessee', value: 520},
		{name: 'Texas', value: 1589},
		{name: 'Utah', value: 46},
		{name: 'Vermont', value: 8},
		{name: 'Virginia', value: 420},
		{name: 'Washington', value: 219},
		{name: 'West Virginia', value: 80},
		{name: 'Wisconsin', value: 164},
		{name: 'Wyoming', value: 12},
	],
	2010:[
		{name: 'Alabama', value: 210},
		{name: 'Alaska', value: 44},
		{name: 'Arizona', value: 429},
		{name: 'Arkansas', value: 155},
		{name: 'California', value: 2111},
		{name: 'Colorado', value: 156},
		{name: 'Connecticut', value: 146},
		{name: 'Delaware', value: 56},
		{name: 'District of Columbia', value: 143},
		{name: 'Florida', value: 1222},
		{name: 'Georgia', value: 615},
		{name: 'Hawaii', value: 32},
		{name: 'Idaho', value: 24},
		{name: 'Illinois', value: 492},
		{name: 'Indiana', value: 324},
		{name: 'Iowa', value: 45},
		{name: 'Kansas', value: 119},
		{name: 'Kentucky', value: 209},
		{name: 'Louisiana', value: 535},
		{name: 'Maine', value: 29},
		{name: 'Maryland', value: 465},
		{name: 'Massachusetts', value: 237},
		{name: 'Michigan', value: 658},
		{name: 'Minnesota', value: 118},
		{name: 'Mississippi', value: 186},
		{name: 'Missouri', value: 490},
		{name: 'Montana', value: 27},
		{name: 'Nebraska', value: 60},
		{name: 'Nevada', value: 197},
		{name: 'New Hampshire', value: 14},
		{name: 'New Jersey', value: 420},
		{name: 'New Mexico', value: 159},
		{name: 'New York', value: 933},
		{name: 'North Carolina', value: 506},
		{name: 'North Dakota', value: 9},
		{name: 'Ohio', value: 510},
		{name: 'Oklahoma', value: 227},
		{name: 'Oregon', value: 101},
		{name: 'Pennsylvania', value: 745},
		{name: 'Rhodes Island', value: 33},
		{name: 'South Carolina', value: 303},
		{name: 'South Dakota', value: 18},
		{name: 'Tennessee', value: 428},
		{name: 'Texas', value: 1470},
		{name: 'Utah', value: 64},
		{name: 'Vermont', value: 7},
		{name: 'Virginia', value: 424},
		{name: 'Washington', value: 186},
		{name: 'West Virginia', value: 61},
		{name: 'Wisconsin', value: 179},
		{name: 'Wyoming', value: 10},
	],
	2011:[
		{name: 'Alabama', value: 0},
		{name: 'Alaska', value: 37},
		{name: 'Arizona', value: 415},
		{name: 'Arkansas', value: 174},
		{name: 'California', value: 2110},
		{name: 'Colorado', value: 182},
		{name: 'Connecticut', value: 138},
		{name: 'Delaware', value: 50},
		{name: 'District of Columbia', value: 125},
		{name: 'Florida', value: 1255},
		{name: 'Georgia', value: 608},
		{name: 'Hawaii', value: 26},
		{name: 'Idaho', value: 33},
		{name: 'Illinois', value: 519},
		{name: 'Indiana', value: 343},
		{name: 'Iowa', value: 57},
		{name: 'Kansas', value: 125},
		{name: 'Kentucky', value: 179},
		{name: 'Louisiana', value: 553},
		{name: 'Maine', value: 36},
		{name: 'Maryland', value: 470},
		{name: 'Massachusetts', value: 200},
		{name: 'Michigan', value: 726},
		{name: 'Minnesota', value: 90},
		{name: 'Mississippi', value: 213},
		{name: 'Missouri', value: 420},
		{name: 'Montana', value: 22},
		{name: 'Nebraska', value: 82},
		{name: 'Nevada', value: 163},
		{name: 'New Hampshire', value: 17},
		{name: 'New Jersey', value: 425},
		{name: 'New Mexico', value: 138},
		{name: 'New York', value: 812},
		{name: 'North Carolina', value: 531},
		{name: 'North Dakota', value: 18},
		{name: 'Ohio', value: 538},
		{name: 'Oklahoma', value: 247},
		{name: 'Oregon', value: 101},
		{name: 'Pennsylvania', value: 749},
		{name: 'Rhodes Island', value: 22},
		{name: 'South Carolina', value: 365},
		{name: 'South Dakota', value: 20},
		{name: 'Tennessee', value: 451},
		{name: 'Texas', value: 1301},
		{name: 'Utah', value: 57},
		{name: 'Vermont', value: 11},
		{name: 'Virginia', value: 347},
		{name: 'Washington', value: 198},
		{name: 'West Virginia', value: 91},
		{name: 'Wisconsin', value: 152},
		{name: 'Wyoming', value: 20},
	],
	2012:[
		{name: 'Alabama', value: 2},
		{name: 'Alaska', value: 42},
		{name: 'Arizona', value: 401},
		{name: 'Arkansas', value: 195},
		{name: 'California', value: 2206},
		{name: 'Colorado', value: 180},
		{name: 'Connecticut', value: 152},
		{name: 'Delaware', value: 61},
		{name: 'District of Columbia', value: 0},
		{name: 'Florida', value: 1267},
		{name: 'Georgia', value: 632},
		{name: 'Hawaii', value: 27},
		{name: 'Idaho', value: 32},
		{name: 'Illinois', value: 568},
		{name: 'Indiana', value: 333},
		{name: 'Iowa', value: 56},
		{name: 'Kansas', value: 98},
		{name: 'Kentucky', value: 218},
		{name: 'Louisiana', value: 570},
		{name: 'Maine', value: 33},
		{name: 'Maryland', value: 427},
		{name: 'Massachusetts', value: 127},
		{name: 'Michigan', value: 799},
		{name: 'Minnesota', value: 120},
		{name: 'Mississippi', value: 191},
		{name: 'Missouri', value: 454},
		{name: 'Montana', value: 28},
		{name: 'Nebraska', value: 61},
		{name: 'Nevada', value: 143},
		{name: 'New Hampshire', value: 17},
		{name: 'New Jersey', value: 435},
		{name: 'New Mexico', value: 127},
		{name: 'New York', value: 728},
		{name: 'North Carolina', value: 549},
		{name: 'North Dakota', value: 15},
		{name: 'Ohio', value: 518},
		{name: 'Oklahoma', value: 258},
		{name: 'Oregon', value: 103},
		{name: 'Pennsylvania', value: 835},
		{name: 'Rhodes Island', value: 42},
		{name: 'South Carolina', value: 374},
		{name: 'South Dakota', value: 18},
		{name: 'Tennessee', value: 474},
		{name: 'Texas', value: 1364},
		{name: 'Utah', value: 60},
		{name: 'Vermont', value: 13},
		{name: 'Virginia', value: 358},
		{name: 'Washington', value: 231},
		{name: 'West Virginia', value: 81},
		{name: 'Wisconsin', value: 194},
		{name: 'Wyoming', value: 18},
	],
	2013:[
		{name: 'Alabama', value: 2},
		{name: 'Alaska', value: 44},
		{name: 'Arizona', value: 416},
		{name: 'Arkansas', value: 177},
		{name: 'California', value: 2085},
		{name: 'Colorado', value: 213},
		{name: 'Connecticut', value: 97},
		{name: 'Delaware', value: 44},
		{name: 'District of Columbia', value: 120},
		{name: 'Florida', value: 1222},
		{name: 'Georgia', value: 624},
		{name: 'Hawaii', value: 28},
		{name: 'Idaho', value: 36},
		{name: 'Illinois', value: 495},
		{name: 'Indiana', value: 380},
		{name: 'Iowa', value: 44},
		{name: 'Kansas', value: 127},
		{name: 'Kentucky', value: 193},
		{name: 'Louisiana', value: 526},
		{name: 'Maine', value: 31},
		{name: 'Maryland', value: 440},
		{name: 'Massachusetts', value: 148},
		{name: 'Michigan', value: 712},
		{name: 'Minnesota', value: 135},
		{name: 'Mississippi', value: 159},
		{name: 'Missouri', value: 447},
		{name: 'Montana', value: 17},
		{name: 'Nebraska', value: 67},
		{name: 'Nevada', value: 186},
		{name: 'New Hampshire', value: 24},
		{name: 'New Jersey', value: 449},
		{name: 'New Mexico', value: 131},
		{name: 'New York', value: 700},
		{name: 'North Carolina', value: 521},
		{name: 'North Dakota', value: 11},
		{name: 'Ohio', value: 510},
		{name: 'Oklahoma', value: 238},
		{name: 'Oregon', value: 90},
		{name: 'Pennsylvania', value: 725},
		{name: 'Rhodes Island', value: 32},
		{name: 'South Carolina', value: 338},
		{name: 'South Dakota', value: 16},
		{name: 'Tennessee', value: 393},
		{name: 'Texas', value: 1372},
		{name: 'Utah', value: 53},
		{name: 'Vermont', value: 12},
		{name: 'Virginia', value: 365},
		{name: 'Washington', value: 205},
		{name: 'West Virginia', value: 65},
		{name: 'Wisconsin', value: 195},
		{name: 'Wyoming', value: 17},
	],
	2014:[
		{name: 'Alabama', value: 1},
		{name: 'Alaska', value: 52},
		{name: 'Arizona', value: 335},
		{name: 'Arkansas', value: 181},
		{name: 'California', value: 2010},
		{name: 'Colorado', value: 188},
		{name: 'Connecticut', value: 99},
		{name: 'Delaware', value: 57},
		{name: 'District of Columbia', value: 128},
		{name: 'Florida', value: 1254},
		{name: 'Georgia', value: 648},
		{name: 'Hawaii', value: 19},
		{name: 'Idaho', value: 31},
		{name: 'Illinois', value: 481},
		{name: 'Indiana', value: 366},
		{name: 'Iowa', value: 68},
		{name: 'Kansas', value: 99},
		{name: 'Kentucky', value: 177},
		{name: 'Louisiana', value: 485},
		{name: 'Maine', value: 29},
		{name: 'Maryland', value: 379},
		{name: 'Massachusetts', value: 150},
		{name: 'Michigan', value: 610},
		{name: 'Minnesota', value: 121},
		{name: 'Mississippi', value: 187},
		{name: 'Missouri', value: 473},
		{name: 'Montana', value: 34},
		{name: 'Nebraska', value: 60},
		{name: 'Nevada', value: 195},
		{name: 'New Hampshire', value: 16},
		{name: 'New Jersey', value: 381},
		{name: 'New Mexico', value: 133},
		{name: 'New York', value: 698},
		{name: 'North Carolina', value: 523},
		{name: 'North Dakota', value: 18},
		{name: 'Ohio', value: 491},
		{name: 'Oklahoma', value: 220},
		{name: 'Oregon', value: 90},
		{name: 'Pennsylvania', value: 705},
		{name: 'Rhodes Island', value: 29},
		{name: 'South Carolina', value: 363},
		{name: 'South Dakota', value: 20},
		{name: 'Tennessee', value: 445},
		{name: 'Texas', value: 1430},
		{name: 'Utah', value: 83},
		{name: 'Vermont', value: 11},
		{name: 'Virginia', value: 381},
		{name: 'Washington', value: 221},
		{name: 'West Virginia', value: 82},
		{name: 'Wisconsin', value: 181},
		{name: 'Wyoming', value: 15},
	],
}